-- 코드를 입력하세요
SELECT CART_ID
FROM CART_PRODUCTS 
WHERE CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'MILK' GROUP BY 1)
    AND CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt' GROUP BY 1) 
GROUP BY 1
ORDER BY 1